### ISSUE TITLE
no update of number of items

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms-extended#11]
When I add an item to the shop it will be displayed as "1 item in basket"
So far so good.
Switching over to checkout:
When I change the number of items to 5 and update the cart and afterward go back via "go on shopping", there still the basket contains 1 item only.
I think that this is kind of a bug?
Please check into it some day ;)
EDIT: some day wasn't meant like never ;)

**Comment by robinsherwood** [comment]
Could you please check that bug? It's kind of quite irritating for customers - they always think they have made a mistake!

**Comment by robinsherwood** [comment]
This will only happen if cart and shop are on *different* pages. With all in one page everything seems to be ok.

**Comment by robinsherwood** [comment]
Is this solved yet? Mostly shop and cart are on different pages, you know

**Comment by slackero** [comment]
shop has moved, no longer related to phpwcms-extended
